import PDFDocument from "pdfkit";

import type {
  InvoiceResponse,
  InvoiceWithClient,
} from "./invoice.types";

export function generateInvoicePdf(
  invoice: InvoiceResponse | InvoiceWithClient
): PDFKit.PDFDocument {
  const doc =
    new PDFDocument({
      size: "A4",
      margin: 50,
    });

  doc
    .fontSize(24)
    .font("Helvetica-Bold")
    .text("NEXUS", {
      align: "left",
    });

  doc
    .fontSize(12)
    .font("Helvetica")
    .text("Billing Portal");

  doc.moveDown(1.5);

  doc
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("INVOICE");

  doc.moveDown(0.5);

  doc
    .fontSize(10)
    .font("Helvetica")
    .text(
      `Invoice Number: ${invoice.invoiceNumber}`
    )
    .text(
      `Issue Date: ${formatDate(
        invoice.issueDate
      )}`
    )
    .text(
      `Due Date: ${formatDate(
        invoice.dueDate
      )}`
    )
    .text(
      `Status: ${invoice.status}`
    )
    .text(
      `Payment Status: ${invoice.paymentStatus}`
    );

  doc.moveDown(1);

  if ("client" in invoice && invoice.client) {
    doc
      .fontSize(11)
      .font("Helvetica-Bold")
      .text("Bill To:");

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(invoice.client.name)
      .text(invoice.client.email);
  }

  doc.moveDown(1.5);

  doc
    .fontSize(10)
    .font("Helvetica-Bold")
    .text(
      "Description",
      50,
      undefined,
      {
        continued: true,
        width: 250,
      }
    )
    .text("Qty", {
      continued: true,
      width: 50,
      align: "right",
    })
    .text("Unit Price", {
      continued: true,
      width: 90,
      align: "right",
    })
    .text("Amount", {
      width: 90,
      align: "right",
    });

  doc.moveTo(50, doc.y + 5)
    .lineTo(545, doc.y + 5)
    .stroke();

  doc.moveDown(0.5);

  invoice.items.forEach((item) => {
    doc
      .fontSize(9)
      .font("Helvetica")
      .text(
        item.description,
        50,
        undefined,
        {
          continued: true,
          width: 250,
        }
      )
      .text(
        item.quantity.toString(),
        {
          continued: true,
          width: 50,
          align: "right",
        }
      )
      .text(
        formatCurrency(
          item.unitPrice,
          invoice.currency
        ),
        {
          continued: true,
          width: 90,
          align: "right",
        }
      )
      .text(
        formatCurrency(
          item.amount,
          invoice.currency
        ),
        {
          width: 90,
          align: "right",
        }
      );

    doc.moveDown(0.5);
  });

  doc.moveDown(1);

  doc
    .fontSize(10)
    .font("Helvetica")
    .text(
      `Subtotal: ${formatCurrency(
        invoice.subtotal,
        invoice.currency
      )}`,
      {
        align: "right",
      }
    )
    .text(
      `Tax (${invoice.taxRate}%): ${formatCurrency(
        invoice.taxAmount,
        invoice.currency
      )}`,
      {
        align: "right",
      }
    );

  doc
    .fontSize(13)
    .font("Helvetica-Bold")
    .text(
      `Total: ${formatCurrency(
        invoice.total,
        invoice.currency
      )}`,
      {
        align: "right",
      }
    );

  doc.moveDown(2);

  doc
    .fontSize(9)
    .font("Helvetica")
    .text(
      "Generated by Nexus Billing Portal",
      {
        align: "center",
      }
    );

  doc.end();

  return doc;
}

function formatDate(
  date: Date
): string {
  return new Date(
    date
  ).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function formatCurrency(
  amount: number,
  currency: string
): string {
  return new Intl.NumberFormat(
    "en-US",
    {
      style: "currency",
      currency,
    }
  ).format(amount);
}